/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.emy.BancoPDLP.view;

import com.mycompany.emy.BancoPDLP.model.dto.ContaPoupanca;
import com.mycompany.emy.BancoPDLP.model.service.ContaBancariaService;
import java.awt.Component;
import java.awt.Container;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JTextField;
import org.springframework.beans.factory.annotation.Autowired;

/**
 *
 * @author emtra
 */
@org.springframework.stereotype.Component
public class TelaInicial extends javax.swing.JFrame {

    @Autowired
    private ContaBancariaService contaBancariaService;

    public TelaInicial(ContaBancariaService contaBancariaService) {
        this.contaBancariaService = contaBancariaService;
    }

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        cadastroContainer = new javax.swing.JPanel();
        telaCadastroContainer = new javax.swing.JPanel();
        cadastroNomeContainer = new javax.swing.JPanel();
        cadastroNomeLabel = new javax.swing.JLabel();
        CadastroNomeInput = new javax.swing.JTextField();
        cadastroSaldoContainer = new javax.swing.JPanel();
        cadastroSaldoLabel = new javax.swing.JLabel();
        cadastroSaldoInput = new javax.swing.JTextField();
        cadastroContaContainer = new javax.swing.JPanel();
        cadastroAgenciaInput = new javax.swing.JTextField();
        cadastroAgenciaLabel = new javax.swing.JLabel();
        cadastroContaLabel = new javax.swing.JLabel();
        cadastroContaInput = new javax.swing.JTextField();
        cadastroTipoContaLabel = new javax.swing.JLabel();
        ccadastroContaPoupancaButton = new javax.swing.JRadioButton();
        cadastroContaCorrentePJButton = new javax.swing.JRadioButton();
        cadastroContaCorrentePfButton = new javax.swing.JRadioButton();
        cadastroButtonContainer = new javax.swing.JPanel();
        cadastrarButton = new javax.swing.JButton();
        cadastroCancelarButton = new javax.swing.JButton();
        operacoesContainer = new javax.swing.JPanel();
        telaOperacoesContainer = new javax.swing.JPanel();
        saldoContainer1 = new javax.swing.JPanel();
        saldoLabel1 = new javax.swing.JLabel();
        saldoInput1 = new javax.swing.JTextField();
        tabOperacoes = new javax.swing.JTabbedPane();
        saqueContainer = new javax.swing.JPanel();
        saqueContainerButton = new javax.swing.JPanel();
        saqueVoltarButton = new javax.swing.JButton();
        saqueCancelarButton = new javax.swing.JButton();
        saqueButton = new javax.swing.JButton();
        saqueContaContainer = new javax.swing.JPanel();
        saqueAgenciaInput = new javax.swing.JTextField();
        saqueAgenciaLabel = new javax.swing.JLabel();
        saqueContaLabel = new javax.swing.JLabel();
        saqueContaInput = new javax.swing.JTextField();
        saqueValorContainer = new javax.swing.JPanel();
        saqueValorLabel = new javax.swing.JLabel();
        saqueValorInput = new javax.swing.JTextField();
        depositoContainer = new javax.swing.JPanel();
        depositoContaContainer = new javax.swing.JPanel();
        depositoAgenciaInput = new javax.swing.JTextField();
        depositoAgenciaLabel = new javax.swing.JLabel();
        depositoContaLabel = new javax.swing.JLabel();
        depositoContaInput = new javax.swing.JTextField();
        depositoContainerButton = new javax.swing.JPanel();
        depositoVoltarButton = new javax.swing.JButton();
        depositoCancelarButton = new javax.swing.JButton();
        depositoButton = new javax.swing.JButton();
        depositoValorContainer = new javax.swing.JPanel();
        depositoValorLabel = new javax.swing.JLabel();
        depositoValorInput = new javax.swing.JTextField();
        transferenciaContainer = new javax.swing.JPanel();
        contaOrigemContainer = new javax.swing.JPanel();
        transferenciaAgenciaOrigemInput = new javax.swing.JTextField();
        transferenciaAgenciaOrigemLabel = new javax.swing.JLabel();
        transferenciaContaOrigemLabel = new javax.swing.JLabel();
        transferenciaContaOrigemInput = new javax.swing.JTextField();
        contaDestinoContainer = new javax.swing.JPanel();
        transferenciaAgenciaDestinoInput = new javax.swing.JTextField();
        transferenciaAgenciaDestinoLabel = new javax.swing.JLabel();
        transferenciaContaDestinoLabel = new javax.swing.JLabel();
        transferenciaContaDestinoInput = new javax.swing.JTextField();
        tansferenciaContainerButton = new javax.swing.JPanel();
        transferenciaVoltarButton = new javax.swing.JButton();
        transferenciaCancelarButton = new javax.swing.JButton();
        transferirButton = new javax.swing.JButton();
        transferenciaValorContainer = new javax.swing.JPanel();
        transferenciaValorLabel = new javax.swing.JLabel();
        transferenciaValorInput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cadastroNomeContainer.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));
        cadastroNomeContainer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        cadastroNomeLabel.setText("Nome:");

        CadastroNomeInput.setToolTipText("John");

        javax.swing.GroupLayout cadastroNomeContainerLayout = new javax.swing.GroupLayout(cadastroNomeContainer);
        cadastroNomeContainer.setLayout(cadastroNomeContainerLayout);
        cadastroNomeContainerLayout.setHorizontalGroup(
            cadastroNomeContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroNomeContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cadastroNomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CadastroNomeInput, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addContainerGap())
        );
        cadastroNomeContainerLayout.setVerticalGroup(
            cadastroNomeContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroNomeContainerLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(cadastroNomeContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastroNomeLabel)
                    .addComponent(CadastroNomeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cadastroSaldoContainer.setBorder(javax.swing.BorderFactory.createTitledBorder("Saldo"));

        cadastroSaldoLabel.setText("Saldo:");

        cadastroSaldoInput.setToolTipText("R$0,00");

        javax.swing.GroupLayout cadastroSaldoContainerLayout = new javax.swing.GroupLayout(cadastroSaldoContainer);
        cadastroSaldoContainer.setLayout(cadastroSaldoContainerLayout);
        cadastroSaldoContainerLayout.setHorizontalGroup(
            cadastroSaldoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroSaldoContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cadastroSaldoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastroSaldoInput)
                .addContainerGap())
        );
        cadastroSaldoContainerLayout.setVerticalGroup(
            cadastroSaldoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroSaldoContainerLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(cadastroSaldoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastroSaldoLabel)
                    .addComponent(cadastroSaldoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        cadastroContaContainer.setBorder(javax.swing.BorderFactory.createTitledBorder("Conta"));

        cadastroAgenciaInput.setToolTipText("XXXX");
        cadastroAgenciaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroAgenciaInputActionPerformed(evt);
            }
        });

        cadastroAgenciaLabel.setText("Agência:");

        cadastroContaLabel.setText("Conta:");

        cadastroContaInput.setToolTipText("XXX");
        cadastroContaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroContaInputActionPerformed(evt);
            }
        });

        cadastroTipoContaLabel.setText("Tipo de conta:");

        ccadastroContaPoupancaButton.setSelected(true);
        ccadastroContaPoupancaButton.setText("Conta Poupança");
        ccadastroContaPoupancaButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        ccadastroContaPoupancaButton.setMargin(new java.awt.Insets(0, 0, 0, 0));

        cadastroContaCorrentePJButton.setText("Conta Corrente PJ");
        cadastroContaCorrentePJButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        cadastroContaCorrentePJButton.setMargin(new java.awt.Insets(0, 0, 0, 0));

        cadastroContaCorrentePfButton.setText("Conta Corrente PF");
        cadastroContaCorrentePfButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        cadastroContaCorrentePfButton.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout cadastroContaContainerLayout = new javax.swing.GroupLayout(cadastroContaContainer);
        cadastroContaContainer.setLayout(cadastroContaContainerLayout);
        cadastroContaContainerLayout.setHorizontalGroup(
            cadastroContaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroContaContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cadastroContaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastroContaContainerLayout.createSequentialGroup()
                        .addComponent(cadastroAgenciaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadastroAgenciaInput)
                        .addGap(24, 24, 24)
                        .addComponent(cadastroContaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadastroContaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(cadastroContaContainerLayout.createSequentialGroup()
                        .addGroup(cadastroContaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cadastroContaContainerLayout.createSequentialGroup()
                                .addComponent(ccadastroContaPoupancaButton)
                                .addGap(12, 12, 12)
                                .addComponent(cadastroContaCorrentePJButton)
                                .addGap(18, 18, 18)
                                .addComponent(cadastroContaCorrentePfButton))
                            .addComponent(cadastroTipoContaLabel))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        cadastroContaContainerLayout.setVerticalGroup(
            cadastroContaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroContaContainerLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(cadastroContaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastroAgenciaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastroAgenciaLabel)
                    .addComponent(cadastroContaLabel)
                    .addComponent(cadastroContaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(cadastroTipoContaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroContaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ccadastroContaPoupancaButton)
                    .addComponent(cadastroContaCorrentePJButton)
                    .addComponent(cadastroContaCorrentePfButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8))
        );

        cadastrarButton.setText("Cadastrar");
        cadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButtonActionPerformed(evt);
            }
        });

        cadastroCancelarButton.setText("Cancelar");
        cadastroCancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroCancelarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cadastroButtonContainerLayout = new javax.swing.GroupLayout(cadastroButtonContainer);
        cadastroButtonContainer.setLayout(cadastroButtonContainerLayout);
        cadastroButtonContainerLayout.setHorizontalGroup(
            cadastroButtonContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroButtonContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cadastrarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastroCancelarButton)
                .addContainerGap())
        );
        cadastroButtonContainerLayout.setVerticalGroup(
            cadastroButtonContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroButtonContainerLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(cadastroButtonContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarButton)
                    .addComponent(cadastroCancelarButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout telaCadastroContainerLayout = new javax.swing.GroupLayout(telaCadastroContainer);
        telaCadastroContainer.setLayout(telaCadastroContainerLayout);
        telaCadastroContainerLayout.setHorizontalGroup(
            telaCadastroContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaCadastroContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(telaCadastroContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cadastroButtonContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(telaCadastroContainerLayout.createSequentialGroup()
                        .addGroup(telaCadastroContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cadastroSaldoContainer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cadastroContaContainer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cadastroNomeContainer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        telaCadastroContainerLayout.setVerticalGroup(
            telaCadastroContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaCadastroContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cadastroNomeContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastroContaContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cadastroSaldoContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 101, Short.MAX_VALUE)
                .addComponent(cadastroButtonContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout cadastroContainerLayout = new javax.swing.GroupLayout(cadastroContainer);
        cadastroContainer.setLayout(cadastroContainerLayout);
        cadastroContainerLayout.setHorizontalGroup(
            cadastroContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(telaCadastroContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        cadastroContainerLayout.setVerticalGroup(
            cadastroContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(telaCadastroContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        jTabbedPane1.addTab("Cadastro", cadastroContainer);

        saldoContainer1.setBorder(javax.swing.BorderFactory.createTitledBorder("Saldo"));

        saldoLabel1.setText("Saldo atual:");

        saldoInput1.setToolTipText("R$0,00");

        javax.swing.GroupLayout saldoContainer1Layout = new javax.swing.GroupLayout(saldoContainer1);
        saldoContainer1.setLayout(saldoContainer1Layout);
        saldoContainer1Layout.setHorizontalGroup(
            saldoContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saldoContainer1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saldoLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saldoInput1)
                .addContainerGap())
        );
        saldoContainer1Layout.setVerticalGroup(
            saldoContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saldoContainer1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(saldoContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saldoLabel1)
                    .addComponent(saldoInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabOperacoes.setName("Saque"); // NOI18N

        saqueVoltarButton.setText("Voltar");
        saqueVoltarButton.setName(""); // NOI18N

        saqueCancelarButton.setText("Cancelar");
        saqueCancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saqueCancelarButtonActionPerformed(evt);
            }
        });

        saqueButton.setText("Sacar");
        saqueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saqueButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout saqueContainerButtonLayout = new javax.swing.GroupLayout(saqueContainerButton);
        saqueContainerButton.setLayout(saqueContainerButtonLayout);
        saqueContainerButtonLayout.setHorizontalGroup(
            saqueContainerButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saqueContainerButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saqueButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saqueVoltarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saqueCancelarButton)
                .addContainerGap())
        );
        saqueContainerButtonLayout.setVerticalGroup(
            saqueContainerButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, saqueContainerButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(saqueContainerButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saqueButton)
                    .addComponent(saqueVoltarButton)
                    .addComponent(saqueCancelarButton))
                .addGap(20, 20, 20))
        );

        saqueContaContainer.setBorder(javax.swing.BorderFactory.createTitledBorder("Conta"));

        saqueAgenciaInput.setToolTipText("XXXX");
        saqueAgenciaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saqueAgenciaInputActionPerformed(evt);
            }
        });

        saqueAgenciaLabel.setText("Agência:");

        saqueContaLabel.setText("Conta:");

        saqueContaInput.setToolTipText("XXX");
        saqueContaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saqueContaInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout saqueContaContainerLayout = new javax.swing.GroupLayout(saqueContaContainer);
        saqueContaContainer.setLayout(saqueContaContainerLayout);
        saqueContaContainerLayout.setHorizontalGroup(
            saqueContaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saqueContaContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saqueAgenciaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saqueAgenciaInput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saqueContaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saqueContaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        saqueContaContainerLayout.setVerticalGroup(
            saqueContaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saqueContaContainerLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(saqueContaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saqueAgenciaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saqueAgenciaLabel)
                    .addComponent(saqueContaLabel)
                    .addComponent(saqueContaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        saqueValorContainer.setBorder(javax.swing.BorderFactory.createTitledBorder("Valor a ser depositado"));

        saqueValorLabel.setText("Valor: R$");

        saqueValorInput.setToolTipText("XXXX");
        saqueValorInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saqueValorInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout saqueValorContainerLayout = new javax.swing.GroupLayout(saqueValorContainer);
        saqueValorContainer.setLayout(saqueValorContainerLayout);
        saqueValorContainerLayout.setHorizontalGroup(
            saqueValorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saqueValorContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saqueValorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saqueValorInput, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        saqueValorContainerLayout.setVerticalGroup(
            saqueValorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saqueValorContainerLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(saqueValorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saqueValorInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saqueValorLabel))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout saqueContainerLayout = new javax.swing.GroupLayout(saqueContainer);
        saqueContainer.setLayout(saqueContainerLayout);
        saqueContainerLayout.setHorizontalGroup(
            saqueContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(saqueContaContainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(saqueContainerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(saqueValorContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        saqueContainerLayout.setVerticalGroup(
            saqueContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saqueContainerLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(saqueContaContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(saqueValorContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(saqueContainerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabOperacoes.addTab("Saque", saqueContainer);

        depositoContaContainer.setBorder(javax.swing.BorderFactory.createTitledBorder("Conta"));

        depositoAgenciaInput.setToolTipText("XXXX");
        depositoAgenciaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositoAgenciaInputActionPerformed(evt);
            }
        });

        depositoAgenciaLabel.setText("Agência:");

        depositoContaLabel.setText("Conta:");

        depositoContaInput.setToolTipText("XXX");
        depositoContaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositoContaInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout depositoContaContainerLayout = new javax.swing.GroupLayout(depositoContaContainer);
        depositoContaContainer.setLayout(depositoContaContainerLayout);
        depositoContaContainerLayout.setHorizontalGroup(
            depositoContaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositoContaContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(depositoAgenciaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(depositoAgenciaInput, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(depositoContaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(depositoContaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        depositoContaContainerLayout.setVerticalGroup(
            depositoContaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositoContaContainerLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(depositoContaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depositoAgenciaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depositoAgenciaLabel)
                    .addComponent(depositoContaLabel)
                    .addComponent(depositoContaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        depositoVoltarButton.setText("Voltar");
        depositoVoltarButton.setName(""); // NOI18N

        depositoCancelarButton.setText("Cancelar");
        depositoCancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositoCancelarButtonActionPerformed(evt);
            }
        });

        depositoButton.setText("Depositar");
        depositoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout depositoContainerButtonLayout = new javax.swing.GroupLayout(depositoContainerButton);
        depositoContainerButton.setLayout(depositoContainerButtonLayout);
        depositoContainerButtonLayout.setHorizontalGroup(
            depositoContainerButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositoContainerButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(depositoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(depositoVoltarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(depositoCancelarButton)
                .addContainerGap())
        );
        depositoContainerButtonLayout.setVerticalGroup(
            depositoContainerButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, depositoContainerButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(depositoContainerButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depositoButton)
                    .addComponent(depositoVoltarButton)
                    .addComponent(depositoCancelarButton))
                .addGap(20, 20, 20))
        );

        depositoValorContainer.setBorder(javax.swing.BorderFactory.createTitledBorder("Valor a ser depositado"));

        depositoValorLabel.setText("Valor: R$");

        depositoValorInput.setToolTipText("XXXX");
        depositoValorInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositoValorInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout depositoValorContainerLayout = new javax.swing.GroupLayout(depositoValorContainer);
        depositoValorContainer.setLayout(depositoValorContainerLayout);
        depositoValorContainerLayout.setHorizontalGroup(
            depositoValorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositoValorContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(depositoValorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(depositoValorInput, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        depositoValorContainerLayout.setVerticalGroup(
            depositoValorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositoValorContainerLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(depositoValorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depositoValorInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depositoValorLabel))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout depositoContainerLayout = new javax.swing.GroupLayout(depositoContainer);
        depositoContainer.setLayout(depositoContainerLayout);
        depositoContainerLayout.setHorizontalGroup(
            depositoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(depositoContainerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(depositoContainerLayout.createSequentialGroup()
                .addGroup(depositoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(depositoValorContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(depositoContainerLayout.createSequentialGroup()
                        .addComponent(depositoContaContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        depositoContainerLayout.setVerticalGroup(
            depositoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositoContainerLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(depositoContaContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(depositoValorContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(depositoContainerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabOperacoes.addTab("Deposito", depositoContainer);

        contaOrigemContainer.setBorder(javax.swing.BorderFactory.createTitledBorder("Conta Origem"));

        transferenciaAgenciaOrigemInput.setToolTipText("XXXX");
        transferenciaAgenciaOrigemInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferenciaAgenciaOrigemInputActionPerformed(evt);
            }
        });

        transferenciaAgenciaOrigemLabel.setText("Agência:");

        transferenciaContaOrigemLabel.setText("Conta:");

        transferenciaContaOrigemInput.setToolTipText("XXX");
        transferenciaContaOrigemInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferenciaContaOrigemInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contaOrigemContainerLayout = new javax.swing.GroupLayout(contaOrigemContainer);
        contaOrigemContainer.setLayout(contaOrigemContainerLayout);
        contaOrigemContainerLayout.setHorizontalGroup(
            contaOrigemContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contaOrigemContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transferenciaAgenciaOrigemLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transferenciaAgenciaOrigemInput, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(transferenciaContaOrigemLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transferenciaContaOrigemInput, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contaOrigemContainerLayout.setVerticalGroup(
            contaOrigemContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contaOrigemContainerLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(contaOrigemContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transferenciaAgenciaOrigemInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transferenciaAgenciaOrigemLabel)
                    .addComponent(transferenciaContaOrigemLabel)
                    .addComponent(transferenciaContaOrigemInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        contaDestinoContainer.setBorder(javax.swing.BorderFactory.createTitledBorder("Conta Destino"));

        transferenciaAgenciaDestinoInput.setToolTipText("XXXX");
        transferenciaAgenciaDestinoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferenciaAgenciaDestinoInputActionPerformed(evt);
            }
        });

        transferenciaAgenciaDestinoLabel.setText("Agência:");

        transferenciaContaDestinoLabel.setText("Conta:");

        transferenciaContaDestinoInput.setToolTipText("XXX");
        transferenciaContaDestinoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferenciaContaDestinoInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contaDestinoContainerLayout = new javax.swing.GroupLayout(contaDestinoContainer);
        contaDestinoContainer.setLayout(contaDestinoContainerLayout);
        contaDestinoContainerLayout.setHorizontalGroup(
            contaDestinoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contaDestinoContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(transferenciaAgenciaDestinoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transferenciaAgenciaDestinoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(transferenciaContaDestinoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transferenciaContaDestinoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        contaDestinoContainerLayout.setVerticalGroup(
            contaDestinoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contaDestinoContainerLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(contaDestinoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transferenciaAgenciaDestinoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transferenciaAgenciaDestinoLabel)
                    .addComponent(transferenciaContaDestinoLabel)
                    .addComponent(transferenciaContaDestinoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        transferenciaVoltarButton.setText("Voltar");
        transferenciaVoltarButton.setName(""); // NOI18N

        transferenciaCancelarButton.setText("Cancelar");
        transferenciaCancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferenciaCancelarButtonActionPerformed(evt);
            }
        });

        transferirButton.setText("Transferir");
        transferirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferirButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tansferenciaContainerButtonLayout = new javax.swing.GroupLayout(tansferenciaContainerButton);
        tansferenciaContainerButton.setLayout(tansferenciaContainerButtonLayout);
        tansferenciaContainerButtonLayout.setHorizontalGroup(
            tansferenciaContainerButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tansferenciaContainerButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transferirButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(transferenciaVoltarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transferenciaCancelarButton)
                .addContainerGap())
        );
        tansferenciaContainerButtonLayout.setVerticalGroup(
            tansferenciaContainerButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tansferenciaContainerButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(tansferenciaContainerButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transferirButton)
                    .addComponent(transferenciaVoltarButton)
                    .addComponent(transferenciaCancelarButton))
                .addGap(20, 20, 20))
        );

        transferenciaValorContainer.setBorder(javax.swing.BorderFactory.createTitledBorder("Valor a ser depositado"));

        transferenciaValorLabel.setText("Valor: R$");

        transferenciaValorInput.setToolTipText("XXXX");
        transferenciaValorInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferenciaValorInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout transferenciaValorContainerLayout = new javax.swing.GroupLayout(transferenciaValorContainer);
        transferenciaValorContainer.setLayout(transferenciaValorContainerLayout);
        transferenciaValorContainerLayout.setHorizontalGroup(
            transferenciaValorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferenciaValorContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transferenciaValorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transferenciaValorInput, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        transferenciaValorContainerLayout.setVerticalGroup(
            transferenciaValorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferenciaValorContainerLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(transferenciaValorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transferenciaValorInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transferenciaValorLabel))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout transferenciaContainerLayout = new javax.swing.GroupLayout(transferenciaContainer);
        transferenciaContainer.setLayout(transferenciaContainerLayout);
        transferenciaContainerLayout.setHorizontalGroup(
            transferenciaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferenciaContainerLayout.createSequentialGroup()
                .addGroup(transferenciaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(contaOrigemContainer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(contaDestinoContainer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(transferenciaValorContainer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tansferenciaContainerButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        transferenciaContainerLayout.setVerticalGroup(
            transferenciaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferenciaContainerLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(contaOrigemContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contaDestinoContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(transferenciaValorContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tansferenciaContainerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabOperacoes.addTab("Transferência", transferenciaContainer);

        javax.swing.GroupLayout telaOperacoesContainerLayout = new javax.swing.GroupLayout(telaOperacoesContainer);
        telaOperacoesContainer.setLayout(telaOperacoesContainerLayout);
        telaOperacoesContainerLayout.setHorizontalGroup(
            telaOperacoesContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaOperacoesContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(telaOperacoesContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saldoContainer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(telaOperacoesContainerLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(tabOperacoes, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)))
                .addContainerGap())
        );
        telaOperacoesContainerLayout.setVerticalGroup(
            telaOperacoesContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaOperacoesContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saldoContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tabOperacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout operacoesContainerLayout = new javax.swing.GroupLayout(operacoesContainer);
        operacoesContainer.setLayout(operacoesContainerLayout);
        operacoesContainerLayout.setHorizontalGroup(
            operacoesContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(operacoesContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(telaOperacoesContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        operacoesContainerLayout.setVerticalGroup(
            operacoesContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(operacoesContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(telaOperacoesContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Operações", operacoesContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limparCamposRecursivamente(Container container) {
        Component[] components = container.getComponents();
        for (Component component : components) {
            if (component instanceof JTextField) {
                ((JTextField) component).setText("");
            } else if (component instanceof Container) {
                // Se for um container, chame a função recursivamente
                limparCamposRecursivamente((Container) component);
            }
        }
    }

    private void limparCampos(ActionEvent e) {
        Component source = (Component) e.getSource();
        if (source instanceof JButton && "Cancelar".equals(((JButton) source).getText())) {
            // Chame a função recursiva para limpar todos os campos de texto
            limparCamposRecursivamente(telaOperacoesContainer);
        }
    }
    private void cadastroAgenciaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroAgenciaInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroAgenciaInputActionPerformed

    private void cadastroContaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroContaInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroContaInputActionPerformed

    private void cadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButtonActionPerformed
        String agencia = cadastroAgenciaInput.getText();
        String conta = cadastroContaInput.getText();
        String nome = CadastroNomeInput.getText();
        Double saldo = Double.valueOf(cadastroSaldoInput.getText());

        if (ccadastroContaPoupancaButton.isSelected()) {
            ContaPoupanca contaPoupanca = new ContaPoupanca(agencia, conta, ccadastroContaPoupancaButton.getText(), nome, saldo);
            contaBancariaService.cadastrarContaBancaria(contaPoupanca);
        }
    }//GEN-LAST:event_cadastrarButtonActionPerformed

    private void saqueCancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saqueCancelarButtonActionPerformed
        limparCampos(evt);
    }//GEN-LAST:event_saqueCancelarButtonActionPerformed

    private void saqueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saqueButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saqueButtonActionPerformed

    private void saqueAgenciaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saqueAgenciaInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saqueAgenciaInputActionPerformed

    private void saqueContaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saqueContaInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saqueContaInputActionPerformed

    private void depositoAgenciaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositoAgenciaInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depositoAgenciaInputActionPerformed

    private void depositoContaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositoContaInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depositoContaInputActionPerformed

    private void depositoCancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositoCancelarButtonActionPerformed
        limparCampos(evt);
    }//GEN-LAST:event_depositoCancelarButtonActionPerformed

    private void depositoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depositoButtonActionPerformed

    private void transferenciaAgenciaOrigemInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferenciaAgenciaOrigemInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transferenciaAgenciaOrigemInputActionPerformed

    private void transferenciaContaOrigemInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferenciaContaOrigemInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transferenciaContaOrigemInputActionPerformed

    private void transferenciaAgenciaDestinoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferenciaAgenciaDestinoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transferenciaAgenciaDestinoInputActionPerformed

    private void transferenciaContaDestinoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferenciaContaDestinoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transferenciaContaDestinoInputActionPerformed

    private void transferenciaCancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferenciaCancelarButtonActionPerformed
        limparCampos(evt);
    }//GEN-LAST:event_transferenciaCancelarButtonActionPerformed

    private void transferirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferirButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transferirButtonActionPerformed

    private void depositoValorInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositoValorInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depositoValorInputActionPerformed

    private void saqueValorInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saqueValorInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saqueValorInputActionPerformed

    private void transferenciaValorInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferenciaValorInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transferenciaValorInputActionPerformed

    private void cadastroCancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroCancelarButtonActionPerformed
       limparCampos(evt);
    }//GEN-LAST:event_cadastroCancelarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CadastroNomeInput;
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JTextField cadastroAgenciaInput;
    private javax.swing.JLabel cadastroAgenciaLabel;
    private javax.swing.JPanel cadastroButtonContainer;
    private javax.swing.JButton cadastroCancelarButton;
    private javax.swing.JPanel cadastroContaContainer;
    private javax.swing.JRadioButton cadastroContaCorrentePJButton;
    private javax.swing.JRadioButton cadastroContaCorrentePfButton;
    private javax.swing.JTextField cadastroContaInput;
    private javax.swing.JLabel cadastroContaLabel;
    private javax.swing.JPanel cadastroContainer;
    private javax.swing.JPanel cadastroNomeContainer;
    private javax.swing.JLabel cadastroNomeLabel;
    private javax.swing.JPanel cadastroSaldoContainer;
    private javax.swing.JTextField cadastroSaldoInput;
    private javax.swing.JLabel cadastroSaldoLabel;
    private javax.swing.JLabel cadastroTipoContaLabel;
    private javax.swing.JRadioButton ccadastroContaPoupancaButton;
    private javax.swing.JPanel contaDestinoContainer;
    private javax.swing.JPanel contaOrigemContainer;
    private javax.swing.JTextField depositoAgenciaInput;
    private javax.swing.JLabel depositoAgenciaLabel;
    private javax.swing.JButton depositoButton;
    private javax.swing.JButton depositoCancelarButton;
    private javax.swing.JPanel depositoContaContainer;
    private javax.swing.JTextField depositoContaInput;
    private javax.swing.JLabel depositoContaLabel;
    private javax.swing.JPanel depositoContainer;
    private javax.swing.JPanel depositoContainerButton;
    private javax.swing.JPanel depositoValorContainer;
    private javax.swing.JTextField depositoValorInput;
    private javax.swing.JLabel depositoValorLabel;
    private javax.swing.JButton depositoVoltarButton;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel operacoesContainer;
    private javax.swing.JPanel saldoContainer1;
    private javax.swing.JTextField saldoInput1;
    private javax.swing.JLabel saldoLabel1;
    private javax.swing.JTextField saqueAgenciaInput;
    private javax.swing.JLabel saqueAgenciaLabel;
    private javax.swing.JButton saqueButton;
    private javax.swing.JButton saqueCancelarButton;
    private javax.swing.JPanel saqueContaContainer;
    private javax.swing.JTextField saqueContaInput;
    private javax.swing.JLabel saqueContaLabel;
    private javax.swing.JPanel saqueContainer;
    private javax.swing.JPanel saqueContainerButton;
    private javax.swing.JPanel saqueValorContainer;
    private javax.swing.JTextField saqueValorInput;
    private javax.swing.JLabel saqueValorLabel;
    private javax.swing.JButton saqueVoltarButton;
    private javax.swing.JTabbedPane tabOperacoes;
    private javax.swing.JPanel tansferenciaContainerButton;
    private javax.swing.JPanel telaCadastroContainer;
    private javax.swing.JPanel telaOperacoesContainer;
    private javax.swing.JTextField transferenciaAgenciaDestinoInput;
    private javax.swing.JLabel transferenciaAgenciaDestinoLabel;
    private javax.swing.JTextField transferenciaAgenciaOrigemInput;
    private javax.swing.JLabel transferenciaAgenciaOrigemLabel;
    private javax.swing.JButton transferenciaCancelarButton;
    private javax.swing.JTextField transferenciaContaDestinoInput;
    private javax.swing.JLabel transferenciaContaDestinoLabel;
    private javax.swing.JTextField transferenciaContaOrigemInput;
    private javax.swing.JLabel transferenciaContaOrigemLabel;
    private javax.swing.JPanel transferenciaContainer;
    private javax.swing.JPanel transferenciaValorContainer;
    private javax.swing.JTextField transferenciaValorInput;
    private javax.swing.JLabel transferenciaValorLabel;
    private javax.swing.JButton transferenciaVoltarButton;
    private javax.swing.JButton transferirButton;
    // End of variables declaration//GEN-END:variables
}
