package com.mycompany.emy.BancoPDLP.view;

import com.mycompany.emy.BancoPDLP.model.dto.ContaBancariaDTO;
import com.mycompany.emy.BancoPDLP.model.dto.ContaCorrentePFDTO;
import com.mycompany.emy.BancoPDLP.model.dto.ContaCorrentePJDTO;
import com.mycompany.emy.BancoPDLP.model.dto.ContaPoupancaDTO;
import com.mycompany.emy.BancoPDLP.model.dto.OperacaoContaDTO;
import com.mycompany.emy.BancoPDLP.model.exception.ContaBancariaNotFoundException;
import com.mycompany.emy.BancoPDLP.model.service.ContaBancariaService;
import com.mycompany.emy.BancoPDLP.model.service.OperacaoContaService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emtra
 */
@org.springframework.stereotype.Component
public class TelaInicial extends javax.swing.JFrame {
    private static final Logger logger = LoggerFactory.getLogger(TelaInicial.class);

    @Autowired
    private ContaBancariaService contaBancariaService;

    @Autowired
    private OperacaoContaService operacaoContaService;

    public TelaInicial(ContaBancariaService contaBancariaService) {
        this.contaBancariaService = contaBancariaService;
    }

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoContabuttonGroup = new javax.swing.ButtonGroup();
        telaInicialContainer = new javax.swing.JPanel();
        tabTelaInicial = new javax.swing.JTabbedPane();
        cadastroContainer = new javax.swing.JPanel();
        telaCadastroContainer = new javax.swing.JPanel();
        cadastroNomeContainer = new javax.swing.JPanel();
        cadastroNomeLabel = new javax.swing.JLabel();
        CadastroNomeInput = new javax.swing.JTextField();
        cadastroSaldoContainer = new javax.swing.JPanel();
        cadastroSaldoLabel = new javax.swing.JLabel();
        cadastroSaldoInput = new javax.swing.JTextField();
        cadastroContaContainer = new javax.swing.JPanel();
        cadastroAgenciaInput = new javax.swing.JTextField();
        cadastroAgenciaLabel = new javax.swing.JLabel();
        cadastroContaLabel = new javax.swing.JLabel();
        cadastroContaInput = new javax.swing.JTextField();
        cadastroTipoContaLabel = new javax.swing.JLabel();
        cadastroContaPoupancaButton = new javax.swing.JRadioButton();
        cadastroContaCorrentePJButton = new javax.swing.JRadioButton();
        cadastroContaCorrentePfButton = new javax.swing.JRadioButton();
        cadastroButtonContainer = new javax.swing.JPanel();
        cadastrarButton = new javax.swing.JButton();
        cadastroCancelarButton = new javax.swing.JButton();
        operacoesContainer = new javax.swing.JPanel();
        telaOperacoesContainer = new javax.swing.JPanel();
        saldoContainer1 = new javax.swing.JPanel();
        saldoAtualLabel = new javax.swing.JLabel();
        saldoAtuallnput = new javax.swing.JTextField();
        tabOperacoes = new javax.swing.JTabbedPane();
        saqueContainer = new javax.swing.JPanel();
        saqueContainerButton = new javax.swing.JPanel();
        saqueVoltarButton = new javax.swing.JButton();
        saqueCancelarButton = new javax.swing.JButton();
        saqueButton = new javax.swing.JButton();
        saqueContaContainer = new javax.swing.JPanel();
        saqueAgenciaInput = new javax.swing.JTextField();
        saqueAgenciaLabel = new javax.swing.JLabel();
        saqueContaLabel = new javax.swing.JLabel();
        saqueContaInput = new javax.swing.JTextField();
        saqueValorContainer = new javax.swing.JPanel();
        saqueValorLabel = new javax.swing.JLabel();
        saqueValorInput = new javax.swing.JTextField();
        depositoContainer = new javax.swing.JPanel();
        depositoContaContainer = new javax.swing.JPanel();
        depositoAgenciaInput = new javax.swing.JTextField();
        depositoAgenciaLabel = new javax.swing.JLabel();
        depositoContaLabel = new javax.swing.JLabel();
        depositoContaInput = new javax.swing.JTextField();
        depositoContainerButton = new javax.swing.JPanel();
        depositoVoltarButton = new javax.swing.JButton();
        depositoCancelarButton = new javax.swing.JButton();
        depositoButton = new javax.swing.JButton();
        depositoValorContainer = new javax.swing.JPanel();
        depositoValorLabel = new javax.swing.JLabel();
        depositoValorInput = new javax.swing.JTextField();
        transferenciaContainer = new javax.swing.JPanel();
        contaOrigemContainer = new javax.swing.JPanel();
        transferenciaAgenciaOrigemInput = new javax.swing.JTextField();
        transferenciaAgenciaOrigemLabel = new javax.swing.JLabel();
        transferenciaContaOrigemLabel = new javax.swing.JLabel();
        transferenciaContaOrigemInput = new javax.swing.JTextField();
        contaDestinoContainer = new javax.swing.JPanel();
        transferenciaAgenciaDestinoInput = new javax.swing.JTextField();
        transferenciaAgenciaDestinoLabel = new javax.swing.JLabel();
        transferenciaContaDestinoLabel = new javax.swing.JLabel();
        transferenciaContaDestinoInput = new javax.swing.JTextField();
        tansferenciaContainerButton = new javax.swing.JPanel();
        transferenciaVoltarButton = new javax.swing.JButton();
        transferenciaCancelarButton = new javax.swing.JButton();
        transferirButton = new javax.swing.JButton();
        transferenciaValorContainer = new javax.swing.JPanel();
        transferenciaValorLabel = new javax.swing.JLabel();
        transferenciaValorInput = new javax.swing.JTextField();
        extratoContainer = new javax.swing.JPanel();
        telaExtratoContainer = new javax.swing.JPanel();
        pesquisaContainer = new javax.swing.JPanel();
        extratoPesquisaContainer = new javax.swing.JPanel();
        extratoAgenciaInput = new javax.swing.JTextField();
        extratoAgenciaLabel = new javax.swing.JLabel();
        extratoContaLabel = new javax.swing.JLabel();
        extratoContaInput = new javax.swing.JTextField();
        extratoPesquisaButton = new javax.swing.JButton();
        extratoTabelaContainer = new javax.swing.JPanel();
        extratoScrollPane = new javax.swing.JScrollPane();
        extratoTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cadastroContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cadastroNomeContainer.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));
        cadastroNomeContainer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        cadastroNomeLabel.setText("Nome:");

        CadastroNomeInput.setToolTipText("John");

        javax.swing.GroupLayout cadastroNomeContainerLayout = new javax.swing.GroupLayout(cadastroNomeContainer);
        cadastroNomeContainer.setLayout(cadastroNomeContainerLayout);
        cadastroNomeContainerLayout.setHorizontalGroup(
            cadastroNomeContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroNomeContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cadastroNomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CadastroNomeInput)
                .addContainerGap())
        );
        cadastroNomeContainerLayout.setVerticalGroup(
            cadastroNomeContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroNomeContainerLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(cadastroNomeContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastroNomeLabel)
                    .addComponent(CadastroNomeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cadastroSaldoContainer.setBorder(javax.swing.BorderFactory.createTitledBorder("Saldo"));

        cadastroSaldoLabel.setText("Saldo:    R$");

        cadastroSaldoInput.setToolTipText("R$0,00");

        javax.swing.GroupLayout cadastroSaldoContainerLayout = new javax.swing.GroupLayout(cadastroSaldoContainer);
        cadastroSaldoContainer.setLayout(cadastroSaldoContainerLayout);
        cadastroSaldoContainerLayout.setHorizontalGroup(
            cadastroSaldoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroSaldoContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cadastroSaldoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastroSaldoInput)
                .addContainerGap())
        );
        cadastroSaldoContainerLayout.setVerticalGroup(
            cadastroSaldoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroSaldoContainerLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(cadastroSaldoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastroSaldoLabel)
                    .addComponent(cadastroSaldoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        cadastroContaContainer.setBorder(javax.swing.BorderFactory.createTitledBorder("Conta"));

        cadastroAgenciaInput.setToolTipText("XXXX");

        cadastroAgenciaLabel.setText("Agência:");

        cadastroContaLabel.setText("Conta:");

        cadastroContaInput.setToolTipText("XXX");

        cadastroTipoContaLabel.setText("Tipo de conta:");

        tipoContabuttonGroup.add(cadastroContaPoupancaButton);
        cadastroContaPoupancaButton.setText("Conta Poupança");
        cadastroContaPoupancaButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        cadastroContaPoupancaButton.setContentAreaFilled(false);
        cadastroContaPoupancaButton.setMargin(new java.awt.Insets(0, 0, 0, 0));

        tipoContabuttonGroup.add(cadastroContaCorrentePJButton);
        cadastroContaCorrentePJButton.setText("Conta Corrente PJ");
        cadastroContaCorrentePJButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        cadastroContaCorrentePJButton.setMargin(new java.awt.Insets(0, 0, 0, 0));

        tipoContabuttonGroup.add(cadastroContaCorrentePfButton);
        cadastroContaCorrentePfButton.setText("Conta Corrente PF");
        cadastroContaCorrentePfButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        cadastroContaCorrentePfButton.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout cadastroContaContainerLayout = new javax.swing.GroupLayout(cadastroContaContainer);
        cadastroContaContainer.setLayout(cadastroContaContainerLayout);
        cadastroContaContainerLayout.setHorizontalGroup(
            cadastroContaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroContaContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cadastroContaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastroContaContainerLayout.createSequentialGroup()
                        .addComponent(cadastroAgenciaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadastroAgenciaInput)
                        .addGap(24, 24, 24)
                        .addComponent(cadastroContaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadastroContaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(cadastroContaContainerLayout.createSequentialGroup()
                        .addGroup(cadastroContaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cadastroContaContainerLayout.createSequentialGroup()
                                .addComponent(cadastroContaPoupancaButton)
                                .addGap(12, 12, 12)
                                .addComponent(cadastroContaCorrentePJButton)
                                .addGap(18, 18, 18)
                                .addComponent(cadastroContaCorrentePfButton))
                            .addComponent(cadastroTipoContaLabel))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        cadastroContaContainerLayout.setVerticalGroup(
            cadastroContaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroContaContainerLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(cadastroContaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastroAgenciaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastroAgenciaLabel)
                    .addComponent(cadastroContaLabel)
                    .addComponent(cadastroContaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(cadastroTipoContaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroContaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastroContaPoupancaButton)
                    .addComponent(cadastroContaCorrentePJButton)
                    .addComponent(cadastroContaCorrentePfButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8))
        );

        cadastrarButton.setText("Cadastrar");
        cadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButtonActionPerformed(evt);
            }
        });

        cadastroCancelarButton.setText("Cancelar");
        cadastroCancelarButton.setToolTipText("");
        cadastroCancelarButton.setName(""); // NOI18N
        cadastroCancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroCancelarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cadastroButtonContainerLayout = new javax.swing.GroupLayout(cadastroButtonContainer);
        cadastroButtonContainer.setLayout(cadastroButtonContainerLayout);
        cadastroButtonContainerLayout.setHorizontalGroup(
            cadastroButtonContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroButtonContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cadastrarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastroCancelarButton)
                .addContainerGap())
        );
        cadastroButtonContainerLayout.setVerticalGroup(
            cadastroButtonContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroButtonContainerLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(cadastroButtonContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarButton)
                    .addComponent(cadastroCancelarButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout telaCadastroContainerLayout = new javax.swing.GroupLayout(telaCadastroContainer);
        telaCadastroContainer.setLayout(telaCadastroContainerLayout);
        telaCadastroContainerLayout.setHorizontalGroup(
            telaCadastroContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaCadastroContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(telaCadastroContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cadastroButtonContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cadastroSaldoContainer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cadastroContaContainer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cadastroNomeContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        telaCadastroContainerLayout.setVerticalGroup(
            telaCadastroContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaCadastroContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cadastroNomeContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastroContaContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cadastroSaldoContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(cadastroButtonContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cadastroContainer.add(telaCadastroContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 420, -1));

        tabTelaInicial.addTab("Cadastro", cadastroContainer);

        operacoesContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        saldoContainer1.setBorder(javax.swing.BorderFactory.createTitledBorder("Saldo"));

        saldoAtualLabel.setText("Saldo atual:");

        saldoAtuallnput.setToolTipText("R$0,00");

        javax.swing.GroupLayout saldoContainer1Layout = new javax.swing.GroupLayout(saldoContainer1);
        saldoContainer1.setLayout(saldoContainer1Layout);
        saldoContainer1Layout.setHorizontalGroup(
            saldoContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saldoContainer1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saldoAtualLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saldoAtuallnput, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        saldoContainer1Layout.setVerticalGroup(
            saldoContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saldoContainer1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(saldoContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saldoAtualLabel)
                    .addComponent(saldoAtuallnput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabOperacoes.setName("Saque"); // NOI18N

        saqueVoltarButton.setText("Voltar");
        saqueVoltarButton.setName(""); // NOI18N

        saqueCancelarButton.setText("Cancelar");
        saqueCancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saqueCancelarButtonActionPerformed(evt);
            }
        });

        saqueButton.setText("Sacar");
        saqueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    saqueButtonActionPerformed(evt);
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
            }
        });

        javax.swing.GroupLayout saqueContainerButtonLayout = new javax.swing.GroupLayout(saqueContainerButton);
        saqueContainerButton.setLayout(saqueContainerButtonLayout);
        saqueContainerButtonLayout.setHorizontalGroup(
            saqueContainerButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saqueContainerButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saqueButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saqueVoltarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saqueCancelarButton)
                .addContainerGap())
        );
        saqueContainerButtonLayout.setVerticalGroup(
            saqueContainerButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, saqueContainerButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(saqueContainerButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saqueButton)
                    .addComponent(saqueVoltarButton)
                    .addComponent(saqueCancelarButton))
                .addGap(20, 20, 20))
        );

        saqueContaContainer.setBorder(javax.swing.BorderFactory.createTitledBorder("Conta"));

        saqueAgenciaInput.setToolTipText("XXXX");

        saqueAgenciaLabel.setText("Agência:");

        saqueContaLabel.setText("Conta:");

        saqueContaInput.setToolTipText("XXX");

        javax.swing.GroupLayout saqueContaContainerLayout = new javax.swing.GroupLayout(saqueContaContainer);
        saqueContaContainer.setLayout(saqueContaContainerLayout);
        saqueContaContainerLayout.setHorizontalGroup(
            saqueContaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saqueContaContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saqueAgenciaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saqueAgenciaInput, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saqueContaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saqueContaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        saqueContaContainerLayout.setVerticalGroup(
            saqueContaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saqueContaContainerLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(saqueContaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saqueAgenciaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saqueAgenciaLabel)
                    .addComponent(saqueContaLabel)
                    .addComponent(saqueContaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        saqueValorContainer.setBorder(javax.swing.BorderFactory.createTitledBorder("Valor a ser sacado"));

        saqueValorLabel.setText("Valor: R$");

        saqueValorInput.setToolTipText("XXXX");

        javax.swing.GroupLayout saqueValorContainerLayout = new javax.swing.GroupLayout(saqueValorContainer);
        saqueValorContainer.setLayout(saqueValorContainerLayout);
        saqueValorContainerLayout.setHorizontalGroup(
            saqueValorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saqueValorContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saqueValorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saqueValorInput, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        saqueValorContainerLayout.setVerticalGroup(
            saqueValorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saqueValorContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(saqueValorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saqueValorInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saqueValorLabel))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout saqueContainerLayout = new javax.swing.GroupLayout(saqueContainer);
        saqueContainer.setLayout(saqueContainerLayout);
        saqueContainerLayout.setHorizontalGroup(
            saqueContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, saqueContainerLayout.createSequentialGroup()
                .addGroup(saqueContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(saqueContainerButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saqueContaContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saqueValorContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        saqueContainerLayout.setVerticalGroup(
            saqueContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saqueContainerLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(saqueContaContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(saqueValorContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(saqueContainerButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabOperacoes.addTab("Saque", saqueContainer);

        depositoContaContainer.setBorder(javax.swing.BorderFactory.createTitledBorder("Conta"));

        depositoAgenciaInput.setToolTipText("XXXX");

        depositoAgenciaLabel.setText("Agência:");

        depositoContaLabel.setText("Conta:");

        depositoContaInput.setToolTipText("XXX");

        javax.swing.GroupLayout depositoContaContainerLayout = new javax.swing.GroupLayout(depositoContaContainer);
        depositoContaContainer.setLayout(depositoContaContainerLayout);
        depositoContaContainerLayout.setHorizontalGroup(
            depositoContaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositoContaContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(depositoAgenciaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(depositoAgenciaInput, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(depositoContaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(depositoContaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        depositoContaContainerLayout.setVerticalGroup(
            depositoContaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositoContaContainerLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(depositoContaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depositoAgenciaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depositoAgenciaLabel)
                    .addComponent(depositoContaLabel)
                    .addComponent(depositoContaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        depositoVoltarButton.setText("Voltar");
        depositoVoltarButton.setName(""); // NOI18N
        depositoVoltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositoVoltarButtonActionPerformed(evt);
            }
        });

        depositoCancelarButton.setText("Cancelar");
        depositoCancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositoCancelarButtonActionPerformed(evt);
            }
        });

        depositoButton.setText("Depositar");
        depositoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    depositoButtonActionPerformed(evt);
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
            }
        });

        javax.swing.GroupLayout depositoContainerButtonLayout = new javax.swing.GroupLayout(depositoContainerButton);
        depositoContainerButton.setLayout(depositoContainerButtonLayout);
        depositoContainerButtonLayout.setHorizontalGroup(
            depositoContainerButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositoContainerButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(depositoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(depositoVoltarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(depositoCancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        depositoContainerButtonLayout.setVerticalGroup(
            depositoContainerButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, depositoContainerButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(depositoContainerButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depositoButton)
                    .addComponent(depositoVoltarButton)
                    .addComponent(depositoCancelarButton))
                .addGap(20, 20, 20))
        );

        depositoValorContainer.setBorder(javax.swing.BorderFactory.createTitledBorder("Valor a ser depositado"));

        depositoValorLabel.setText("Valor: R$");

        depositoValorInput.setToolTipText("XXXX");

        javax.swing.GroupLayout depositoValorContainerLayout = new javax.swing.GroupLayout(depositoValorContainer);
        depositoValorContainer.setLayout(depositoValorContainerLayout);
        depositoValorContainerLayout.setHorizontalGroup(
            depositoValorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositoValorContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(depositoValorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(depositoValorInput, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        depositoValorContainerLayout.setVerticalGroup(
            depositoValorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositoValorContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(depositoValorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depositoValorInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depositoValorLabel))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout depositoContainerLayout = new javax.swing.GroupLayout(depositoContainer);
        depositoContainer.setLayout(depositoContainerLayout);
        depositoContainerLayout.setHorizontalGroup(
            depositoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositoContainerLayout.createSequentialGroup()
                .addGroup(depositoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(depositoContaContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(depositoValorContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(depositoContainerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        depositoContainerLayout.setVerticalGroup(
            depositoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositoContainerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(depositoContaContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(depositoValorContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(depositoContainerButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabOperacoes.addTab("Deposito", depositoContainer);

        contaOrigemContainer.setBorder(javax.swing.BorderFactory.createTitledBorder("Conta Origem"));

        transferenciaAgenciaOrigemInput.setToolTipText("XXXX");

        transferenciaAgenciaOrigemLabel.setText("Agência:");

        transferenciaContaOrigemLabel.setText("Conta:");

        transferenciaContaOrigemInput.setToolTipText("XXX");

        javax.swing.GroupLayout contaOrigemContainerLayout = new javax.swing.GroupLayout(contaOrigemContainer);
        contaOrigemContainer.setLayout(contaOrigemContainerLayout);
        contaOrigemContainerLayout.setHorizontalGroup(
            contaOrigemContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contaOrigemContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transferenciaAgenciaOrigemLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transferenciaAgenciaOrigemInput, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(transferenciaContaOrigemLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transferenciaContaOrigemInput)
                .addContainerGap())
        );
        contaOrigemContainerLayout.setVerticalGroup(
            contaOrigemContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contaOrigemContainerLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(contaOrigemContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transferenciaAgenciaOrigemInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transferenciaAgenciaOrigemLabel)
                    .addComponent(transferenciaContaOrigemLabel)
                    .addComponent(transferenciaContaOrigemInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contaDestinoContainer.setBorder(javax.swing.BorderFactory.createTitledBorder("Conta Destino"));

        transferenciaAgenciaDestinoInput.setToolTipText("XXXX");

        transferenciaAgenciaDestinoLabel.setText("Agência:");

        transferenciaContaDestinoLabel.setText("Conta:");

        transferenciaContaDestinoInput.setToolTipText("XXX");

        javax.swing.GroupLayout contaDestinoContainerLayout = new javax.swing.GroupLayout(contaDestinoContainer);
        contaDestinoContainer.setLayout(contaDestinoContainerLayout);
        contaDestinoContainerLayout.setHorizontalGroup(
            contaDestinoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contaDestinoContainerLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(transferenciaAgenciaDestinoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transferenciaAgenciaDestinoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(transferenciaContaDestinoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transferenciaContaDestinoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        contaDestinoContainerLayout.setVerticalGroup(
            contaDestinoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contaDestinoContainerLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(contaDestinoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transferenciaAgenciaDestinoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transferenciaAgenciaDestinoLabel)
                    .addComponent(transferenciaContaDestinoLabel)
                    .addComponent(transferenciaContaDestinoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        transferenciaVoltarButton.setText("Voltar");
        transferenciaVoltarButton.setName(""); // NOI18N

        transferenciaCancelarButton.setText("Cancelar");
        transferenciaCancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferenciaCancelarButtonActionPerformed(evt);
            }
        });

        transferirButton.setText("Transferir");
        transferirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    transferirButtonActionPerformed(evt);
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
            }
        });

        javax.swing.GroupLayout tansferenciaContainerButtonLayout = new javax.swing.GroupLayout(tansferenciaContainerButton);
        tansferenciaContainerButton.setLayout(tansferenciaContainerButtonLayout);
        tansferenciaContainerButtonLayout.setHorizontalGroup(
            tansferenciaContainerButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tansferenciaContainerButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transferirButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(transferenciaVoltarButton)
                .addGap(18, 18, 18)
                .addComponent(transferenciaCancelarButton)
                .addContainerGap())
        );
        tansferenciaContainerButtonLayout.setVerticalGroup(
            tansferenciaContainerButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tansferenciaContainerButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tansferenciaContainerButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transferirButton)
                    .addComponent(transferenciaVoltarButton)
                    .addComponent(transferenciaCancelarButton))
                .addGap(0, 26, Short.MAX_VALUE))
        );

        transferenciaValorContainer.setBorder(javax.swing.BorderFactory.createTitledBorder("Valor a ser transferido"));

        transferenciaValorLabel.setText("Valor: R$");

        transferenciaValorInput.setToolTipText("XXXX");

        javax.swing.GroupLayout transferenciaValorContainerLayout = new javax.swing.GroupLayout(transferenciaValorContainer);
        transferenciaValorContainer.setLayout(transferenciaValorContainerLayout);
        transferenciaValorContainerLayout.setHorizontalGroup(
            transferenciaValorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferenciaValorContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transferenciaValorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transferenciaValorInput, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        transferenciaValorContainerLayout.setVerticalGroup(
            transferenciaValorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transferenciaValorContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(transferenciaValorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transferenciaValorInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transferenciaValorLabel))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout transferenciaContainerLayout = new javax.swing.GroupLayout(transferenciaContainer);
        transferenciaContainer.setLayout(transferenciaContainerLayout);
        transferenciaContainerLayout.setHorizontalGroup(
            transferenciaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contaOrigemContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(transferenciaValorContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contaDestinoContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tansferenciaContainerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        transferenciaContainerLayout.setVerticalGroup(
            transferenciaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferenciaContainerLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(contaOrigemContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contaDestinoContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(transferenciaValorContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tansferenciaContainerButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        tabOperacoes.addTab("Transferência", transferenciaContainer);

        javax.swing.GroupLayout telaOperacoesContainerLayout = new javax.swing.GroupLayout(telaOperacoesContainer);
        telaOperacoesContainer.setLayout(telaOperacoesContainerLayout);
        telaOperacoesContainerLayout.setHorizontalGroup(
            telaOperacoesContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaOperacoesContainerLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(telaOperacoesContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saldoContainer1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tabOperacoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        telaOperacoesContainerLayout.setVerticalGroup(
            telaOperacoesContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaOperacoesContainerLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(saldoContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabOperacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        operacoesContainer.add(telaOperacoesContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, -1));

        tabTelaInicial.addTab("Operações", operacoesContainer);

        extratoPesquisaContainer.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar"));

        extratoAgenciaInput.setToolTipText("XXXX");

        extratoAgenciaLabel.setText("Agência:");

        extratoContaLabel.setText("Conta:");

        extratoContaInput.setToolTipText("XXX");

        extratoPesquisaButton.setText("Pesquisar");
        extratoPesquisaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extratoPesquisaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout extratoPesquisaContainerLayout = new javax.swing.GroupLayout(extratoPesquisaContainer);
        extratoPesquisaContainer.setLayout(extratoPesquisaContainerLayout);
        extratoPesquisaContainerLayout.setHorizontalGroup(
            extratoPesquisaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(extratoPesquisaContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(extratoPesquisaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(extratoPesquisaContainerLayout.createSequentialGroup()
                        .addComponent(extratoAgenciaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(extratoAgenciaInput, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(extratoContaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(extratoContaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(extratoPesquisaContainerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(extratoPesquisaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );
        extratoPesquisaContainerLayout.setVerticalGroup(
            extratoPesquisaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(extratoPesquisaContainerLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(extratoPesquisaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(extratoAgenciaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(extratoAgenciaLabel)
                    .addComponent(extratoContaLabel)
                    .addComponent(extratoContaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(extratoPesquisaButton)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pesquisaContainerLayout = new javax.swing.GroupLayout(pesquisaContainer);
        pesquisaContainer.setLayout(pesquisaContainerLayout);
        pesquisaContainerLayout.setHorizontalGroup(
            pesquisaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pesquisaContainerLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(extratoPesquisaContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        pesquisaContainerLayout.setVerticalGroup(
            pesquisaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pesquisaContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(extratoPesquisaContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        extratoTable.setAutoCreateRowSorter(true);
        extratoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "1", "123", "12.3", "T", "Transferencia"},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "ID_CONTA_BANCARIA", "DATA_HORA", "VALOR", "TP_OPERACAO", "OBSERVACAO"
            }
        ));
        extratoScrollPane.setViewportView(extratoTable);

        javax.swing.GroupLayout extratoTabelaContainerLayout = new javax.swing.GroupLayout(extratoTabelaContainer);
        extratoTabelaContainer.setLayout(extratoTabelaContainerLayout);
        extratoTabelaContainerLayout.setHorizontalGroup(
            extratoTabelaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(extratoTabelaContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(extratoScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        extratoTabelaContainerLayout.setVerticalGroup(
            extratoTabelaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(extratoTabelaContainerLayout.createSequentialGroup()
                .addComponent(extratoScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout telaExtratoContainerLayout = new javax.swing.GroupLayout(telaExtratoContainer);
        telaExtratoContainer.setLayout(telaExtratoContainerLayout);
        telaExtratoContainerLayout.setHorizontalGroup(
            telaExtratoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaExtratoContainerLayout.createSequentialGroup()
                .addGroup(telaExtratoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, telaExtratoContainerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(extratoTabelaContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pesquisaContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        telaExtratoContainerLayout.setVerticalGroup(
            telaExtratoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaExtratoContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pesquisaContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(extratoTabelaContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout extratoContainerLayout = new javax.swing.GroupLayout(extratoContainer);
        extratoContainer.setLayout(extratoContainerLayout);
        extratoContainerLayout.setHorizontalGroup(
            extratoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(extratoContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(telaExtratoContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        extratoContainerLayout.setVerticalGroup(
            extratoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(extratoContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(telaExtratoContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabTelaInicial.addTab("Extrato", extratoContainer);

        javax.swing.GroupLayout telaInicialContainerLayout = new javax.swing.GroupLayout(telaInicialContainer);
        telaInicialContainer.setLayout(telaInicialContainerLayout);
        telaInicialContainerLayout.setHorizontalGroup(
            telaInicialContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaInicialContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabTelaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        telaInicialContainerLayout.setVerticalGroup(
            telaInicialContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaInicialContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabTelaInicial)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(telaInicialContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaInicialContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limparCamposRecursivamente(Container container) {
        Component[] components = container.getComponents();
        for (Component component : components) {
            if (component instanceof JTextField) {
                ((JTextField) component).setText("");
            } else if (component instanceof Container) {
                // Se for um container, chame a função recursivamente
                limparCamposRecursivamente((Container) component);
            }
        }
    }

    private void limparCampos(ActionEvent e) {
        Component source = (Component) e.getSource();
        if (source instanceof JButton && "Cancelar".equals(((JButton) source).getText())) {
            // Chame a função recursiva para limpar todos os campos de texto
            limparCamposRecursivamente(telaInicialContainer);
        }
    }

    private void cadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButtonActionPerformed
        logger.info("TelaInicial - cadastrarButtonActionPerformed: Cadastrando conta");

        ContaBancariaDTO contaBancariaDTO = null;
        String agencia = cadastroAgenciaInput.getText();
        String conta = cadastroContaInput.getText();
        String nome = CadastroNomeInput.getText();
        Double saldo = Double.valueOf(cadastroSaldoInput.getText());
        String tipoConta = "";

        logger.info("TelaInicial - cadastrarButtonActionPerformed: Procurando conta: Agencia:- {}, Conta:- {}, Nome: - {}, Saldo: - {}", agencia, conta, nome, saldo);
        if (cadastroContaPoupancaButton.isSelected()) {
            tipoConta = cadastroContaPoupancaButton.getText();
            contaBancariaDTO = new ContaPoupancaDTO();
        } else if (cadastroContaCorrentePfButton.isSelected()) {
            tipoConta = cadastroContaCorrentePfButton.getText();
            contaBancariaDTO = new ContaCorrentePFDTO();
        } else if (cadastroContaCorrentePJButton.isSelected()) {
            tipoConta = cadastroContaCorrentePJButton.getText();
            contaBancariaDTO = new ContaCorrentePJDTO();
        }
        logger.info("TelaInicial - cadastrarButtonActionPerformed: Tipo da Conta - {}", contaBancariaDTO.getTipoConta());

        if (!tipoConta.isEmpty()) {
            contaBancariaDTO.setAgencia(agencia);
            contaBancariaDTO.setConta(conta);
            contaBancariaDTO.setNome(nome);
            contaBancariaDTO.setTipoConta(tipoConta);
            contaBancariaDTO.setSaldo(saldo);
            contaBancariaService.cadastrarContaBancaria(contaBancariaDTO);
        } else {
            throw new ContaBancariaNotFoundException("Erro ao criar conta");
        }

    }//GEN-LAST:event_cadastrarButtonActionPerformed

    private void cadastroCancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroCancelarButtonActionPerformed
        logger.info("TelaInicial - cadastroCancelarButtonActionPerformed: Cancelando operação");
        limparCampos(evt);
    }//GEN-LAST:event_cadastroCancelarButtonActionPerformed

    private void transferirButtonActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_transferirButtonActionPerformed
        logger.info("TelaInicial - transferirButtonActionPerformed: Realizando transferencia");

        Double valorTransferencia = Double.valueOf(transferenciaValorInput.getText());
        String agenciaOrigem = transferenciaAgenciaOrigemInput.getText();
        String contaOrigem = transferenciaContaOrigemInput.getText();

        String agenciaDestino = transferenciaAgenciaDestinoInput.getText();
        String contaDestino = transferenciaContaDestinoInput.getText();
        logger.info("TelaInicial - depositoButtonActionPerformed: Realizando transferencia de -{}R$, Agencia origem: - {}, Conta origem: - {} para -> Agencia destino: - {}, Conta destino: - {} ",valorTransferencia, agenciaOrigem, contaOrigem, agenciaDestino, contaDestino);

        ContaBancariaDTO contaBancariaOrigem = contaBancariaService.consultarContaDTO(agenciaOrigem,contaOrigem);
        ContaBancariaDTO contaBancariaDestino = contaBancariaService.consultarContaDTO(agenciaDestino,contaDestino);

        logger.info("TelaInicial - depositoButtonActionPerformed: Realizando transferencia de R${}, Conta origem: - {} para -> Conta destino: - {} ",valorTransferencia, contaBancariaOrigem, contaBancariaDestino );

        contaBancariaService.transferir(contaBancariaOrigem,contaBancariaDestino, BigDecimal.valueOf(valorTransferencia));

        BigDecimal saldoAtual = contaBancariaService.consultarSaldo(agenciaOrigem,contaOrigem); // Substitua isso pela forma como você recupera o saldo real.
        String saldoAtualFormatado = String.format("R$%.2f", saldoAtual);
        saldoAtuallnput.setText(saldoAtualFormatado);
    }//GEN-LAST:event_transferirButtonActionPerformed

    private void transferenciaCancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferenciaCancelarButtonActionPerformed
        logger.info("TelaInicial - transferenciaCancelarButtonActionPerformed: Cancelando operação");
        limparCampos(evt);
    }//GEN-LAST:event_transferenciaCancelarButtonActionPerformed

    private void depositoButtonActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_depositoButtonActionPerformed
        logger.info("TelaInicial - depositoButtonActionPerformed: Realizando deposito");
        String agencia = depositoAgenciaInput.getText();
        String conta = depositoContaInput.getText();
        Double valorDeposito = Double.valueOf(depositoValorInput.getText());

        logger.info("TelaInicial - depositoButtonActionPerformed: Realizando deposito de R${}, Agencia: - {}, Conta: - {}",valorDeposito, agencia, conta);
        ContaBancariaDTO contaBancaria = contaBancariaService.consultarContaDTO(agencia,conta);

        contaBancariaService.realizarDeposito(contaBancaria, BigDecimal.valueOf(valorDeposito));

        BigDecimal saldoAtual = contaBancariaService.consultarSaldo(agencia,conta); // Substitua isso pela forma como você recupera o saldo real.
        String saldoAtualFormatado = String.format("R$%.2f", saldoAtual);
        saldoAtuallnput.setText(saldoAtualFormatado);

    }//GEN-LAST:event_depositoButtonActionPerformed

    private void depositoCancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositoCancelarButtonActionPerformed
        logger.info("TelaInicial - depositoCancelarButtonActionPerformed: Cancelando operação");
        limparCampos(evt);
    }//GEN-LAST:event_depositoCancelarButtonActionPerformed

    private void saqueButtonActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_saqueButtonActionPerformed
        logger.info("TelaInicial - saqueButtonActionPerformed: Realizando saque");
        String agencia = saqueAgenciaInput.getText();
        String conta = saqueContaInput.getText();
        Double valorSaque = Double.valueOf(saqueValorInput.getText());

        logger.info("TelaInicial - saqueButtonActionPerformed: Realizando saque de R${}, Agencia: - {}, Conta: - {}",valorSaque, agencia, conta);
        ContaBancariaDTO contaBancaria = contaBancariaService.consultarContaDTO(agencia,conta);

        contaBancariaService.realizarSaque(contaBancaria, BigDecimal.valueOf(valorSaque));

        BigDecimal saldoAtual = contaBancariaService.consultarSaldo(agencia,conta); // Substitua isso pela forma como você recupera o saldo real.
        String saldoAtualFormatado = String.format("R$%.2f", saldoAtual);
        saldoAtuallnput.setText(saldoAtualFormatado);
    }//GEN-LAST:event_saqueButtonActionPerformed

    private void saqueCancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saqueCancelarButtonActionPerformed
        limparCampos(evt);
    }//GEN-LAST:event_saqueCancelarButtonActionPerformed

    private void depositoVoltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositoVoltarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depositoVoltarButtonActionPerformed

    private void atualizarTabela(List<OperacaoContaDTO> operacoes) {
    DefaultTableModel model = (DefaultTableModel) extratoTable.getModel();
    
    // Limpe os dados existentes na tabela
    model.setRowCount(0);
    
    // Preencha a tabela com os resultados da pesquisa
    for (OperacaoContaDTO operacao : operacoes) {
        // "ID, ID_CONTA_BANCARIA","DATA_HORA","VALOR","TP_OPERACAO","OBSERVACAO"
        Object[] rowData = {
            operacao.getId(),
            operacao.getContaBancariaId().getId(),
            operacao.getDataHora(),
            operacao.getValor(),
            operacao.getTpOperacao(),
            operacao.getObservacao()
        };
        model.addRow(rowData);
    }
}
    
    private void extratoPesquisaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extratoPesquisaButtonActionPerformed
        // Captura os valores dos campos de entrada
        String agencia = extratoAgenciaInput.getText();
        String conta = extratoContaInput.getText();

        // Realize a pesquisa com base nos valores capturados
        java.util.List<OperacaoContaDTO> operacoes = operacaoContaService.pesquisarOperacoes(agencia, conta);

        // Atualize a tabela com os resultados
        atualizarTabela(operacoes);
    }//GEN-LAST:event_extratoPesquisaButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CadastroNomeInput;
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JTextField cadastroAgenciaInput;
    private javax.swing.JLabel cadastroAgenciaLabel;
    private javax.swing.JPanel cadastroButtonContainer;
    private javax.swing.JButton cadastroCancelarButton;
    private javax.swing.JPanel cadastroContaContainer;
    private javax.swing.JRadioButton cadastroContaCorrentePJButton;
    private javax.swing.JRadioButton cadastroContaCorrentePfButton;
    private javax.swing.JTextField cadastroContaInput;
    private javax.swing.JLabel cadastroContaLabel;
    private javax.swing.JRadioButton cadastroContaPoupancaButton;
    private javax.swing.JPanel cadastroContainer;
    private javax.swing.JPanel cadastroNomeContainer;
    private javax.swing.JLabel cadastroNomeLabel;
    private javax.swing.JPanel cadastroSaldoContainer;
    private javax.swing.JTextField cadastroSaldoInput;
    private javax.swing.JLabel cadastroSaldoLabel;
    private javax.swing.JLabel cadastroTipoContaLabel;
    private javax.swing.JPanel contaDestinoContainer;
    private javax.swing.JPanel contaOrigemContainer;
    private javax.swing.JTextField depositoAgenciaInput;
    private javax.swing.JLabel depositoAgenciaLabel;
    private javax.swing.JButton depositoButton;
    private javax.swing.JButton depositoCancelarButton;
    private javax.swing.JPanel depositoContaContainer;
    private javax.swing.JTextField depositoContaInput;
    private javax.swing.JLabel depositoContaLabel;
    private javax.swing.JPanel depositoContainer;
    private javax.swing.JPanel depositoContainerButton;
    private javax.swing.JPanel depositoValorContainer;
    private javax.swing.JTextField depositoValorInput;
    private javax.swing.JLabel depositoValorLabel;
    private javax.swing.JButton depositoVoltarButton;
    private javax.swing.JTextField extratoAgenciaInput;
    private javax.swing.JLabel extratoAgenciaLabel;
    private javax.swing.JTextField extratoContaInput;
    private javax.swing.JLabel extratoContaLabel;
    private javax.swing.JPanel extratoContainer;
    private javax.swing.JButton extratoPesquisaButton;
    private javax.swing.JPanel extratoPesquisaContainer;
    private javax.swing.JScrollPane extratoScrollPane;
    private javax.swing.JPanel extratoTabelaContainer;
    private javax.swing.JTable extratoTable;
    private javax.swing.JPanel operacoesContainer;
    private javax.swing.JPanel pesquisaContainer;
    private javax.swing.JLabel saldoAtualLabel;
    private javax.swing.JTextField saldoAtuallnput;
    private javax.swing.JPanel saldoContainer1;
    private javax.swing.JTextField saqueAgenciaInput;
    private javax.swing.JLabel saqueAgenciaLabel;
    private javax.swing.JButton saqueButton;
    private javax.swing.JButton saqueCancelarButton;
    private javax.swing.JPanel saqueContaContainer;
    private javax.swing.JTextField saqueContaInput;
    private javax.swing.JLabel saqueContaLabel;
    private javax.swing.JPanel saqueContainer;
    private javax.swing.JPanel saqueContainerButton;
    private javax.swing.JPanel saqueValorContainer;
    private javax.swing.JTextField saqueValorInput;
    private javax.swing.JLabel saqueValorLabel;
    private javax.swing.JButton saqueVoltarButton;
    private javax.swing.JTabbedPane tabOperacoes;
    private javax.swing.JTabbedPane tabTelaInicial;
    private javax.swing.JPanel tansferenciaContainerButton;
    private javax.swing.JPanel telaCadastroContainer;
    private javax.swing.JPanel telaExtratoContainer;
    private javax.swing.JPanel telaInicialContainer;
    private javax.swing.JPanel telaOperacoesContainer;
    private javax.swing.ButtonGroup tipoContabuttonGroup;
    private javax.swing.JTextField transferenciaAgenciaDestinoInput;
    private javax.swing.JLabel transferenciaAgenciaDestinoLabel;
    private javax.swing.JTextField transferenciaAgenciaOrigemInput;
    private javax.swing.JLabel transferenciaAgenciaOrigemLabel;
    private javax.swing.JButton transferenciaCancelarButton;
    private javax.swing.JTextField transferenciaContaDestinoInput;
    private javax.swing.JLabel transferenciaContaDestinoLabel;
    private javax.swing.JTextField transferenciaContaOrigemInput;
    private javax.swing.JLabel transferenciaContaOrigemLabel;
    private javax.swing.JPanel transferenciaContainer;
    private javax.swing.JPanel transferenciaValorContainer;
    private javax.swing.JTextField transferenciaValorInput;
    private javax.swing.JLabel transferenciaValorLabel;
    private javax.swing.JButton transferenciaVoltarButton;
    private javax.swing.JButton transferirButton;
    // End of variables declaration//GEN-END:variables
}
